In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as ticker
import matplotlib.ticker as plticker
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from datetime import datetime as dt
import itertools

%matplotlib inline

In [25]:
#load data 
world_cup = pd.read_csv('../datasets/World Cup 2018 Dataset.csv')
results = pd.read_csv('../datasets/results.csv')
ranking = pd.read_csv('../datasets/fifa_rankings.csv')
loc ='../datasets/England_result/'

In [3]:
#Adding goal difference and establishing who is the winner 
winner = []
for i in range (len(results['home_team'])):
    if results ['home_score'][i] > results['away_score'][i]:
        winner.append(results['home_team'][i])
    elif results['home_score'][i] < results ['away_score'][i]:
        winner.append(results['away_team'][i])
    else:
        winner.append('Draw')
results['winning_team'] = winner

#adding goal difference column
results['goal_difference'] = np.absolute(results['home_score'] - results['away_score'])

results.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,winning_team,goal_difference
0,1872-11-30,Scotland,England,0,0,Friendly,Glasgow,Scotland,Draw,0
1,1873-03-08,England,Scotland,4,2,Friendly,London,England,England,2
2,1874-03-07,Scotland,England,2,1,Friendly,Glasgow,Scotland,Scotland,1
3,1875-03-06,England,Scotland,2,2,Friendly,London,England,Draw,0
4,1876-03-04,Scotland,England,3,0,Friendly,Glasgow,Scotland,Scotland,3

In [4]:
new_result = results.drop(['date','home_score','away_score','tournament','city','country'],axis=1)
new_result.head()

  home_team away_team winning_team  goal_difference
0  Scotland   England         Draw                0
1   England  Scotland      England                2
2  Scotland   England     Scotland                1
3   England  Scotland         Draw                0
4  Scotland   England     Scotland                3

In [5]:
home_winner = new_result[(new_result.home_team == new_result.winning_team) & (new_result.goal_difference > 0)].iloc[:]
print(home_winner.shape)
print(new_result.shape)

print("In genral {} % of the matches win by the home teams".format(home_winner.shape[0]/new_result.shape[0] *100))

(18765, 4)
(38902, 4)
In genral 48.236594519561976 % of the matches win by the home teams

In [6]:
ranking.head()

   Position       Team  Points
0         1    Germany  1533.0
1         2     Brazil  1384.0
2         3    Belgium  1346.0
3         4   Portugal  1306.0
4         5  Argentina  1254.0

In [7]:
# Create new columns with ranking position of each team
new_result.insert(2, 'rank_hometeam', new_result['home_team'].map(ranking.set_index('Team')['Position']))
new_result.insert(3, 'rank_awayteam', new_result['away_team'].map(ranking.set_index('Team')['Position']))

In [8]:
new_result.head()

,home_team,away_team,rank_hometeam,rank_awayteam,winning_team,goal_difference
0,Scotland,England,34.0,13.0,Draw,0
1,England,Scotland,13.0,34.0,England,2
2,Scotland,England,34.0,13.0,Scotland,1
3,England,Scotland,13.0,34.0,Draw,0
4,Scotland,England,34.0,13.0,Scotland,3

In [20]:
# rank_hometeam>rank_awayteam -> 0 else 1
new_result['rank'] = np.where(new_result['rank_hometeam'] > new_result['rank_awayteam'],0,1)

In [21]:
new_result.head()

,home_team,away_team,rank_hometeam,rank_awayteam,winning_team,goal_difference,rank
0,Scotland,England,34.0,13.0,Draw,0,0
1,England,Scotland,13.0,34.0,England,2,1
2,Scotland,England,34.0,13.0,Scotland,1,0
3,England,Scotland,13.0,34.0,Draw,0,1
4,Scotland,England,34.0,13.0,Scotland,3,0

# new England Football Results

In [30]:
#for understanding the data please check the http://www.football-data.co.uk/notes.txt

# Read data from the CSV into a dataframe


raw_data_1 = pd.read_csv(loc + '2000-01.csv',error_bad_lines=False)
raw_data_2 = pd.read_csv(loc + '2001-02.csv',error_bad_lines=False)
raw_data_3 = pd.read_csv(loc + '2002-03.csv',error_bad_lines=False)
raw_data_4 = pd.read_csv(loc + '2003-04.csv',error_bad_lines=False)
raw_data_5 = pd.read_csv(loc + '2004-05.csv',error_bad_lines=False)
raw_data_6 = pd.read_csv(loc + '2005-06.csv',error_bad_lines=False)
raw_data_7 = pd.read_csv(loc + '2006-07.csv',error_bad_lines=False)
raw_data_8 = pd.read_csv(loc + '2007-08.csv',error_bad_lines=False)
raw_data_9 = pd.read_csv(loc + '2008-09.csv',error_bad_lines=False)
raw_data_10 = pd.read_csv(loc + '2009-10.csv',error_bad_lines=False)
raw_data_11 = pd.read_csv(loc + '2010-11.csv',error_bad_lines=False)
raw_data_12 = pd.read_csv(loc + '2011-12.csv',error_bad_lines=False)
raw_data_13 = pd.read_csv(loc + '2012-13.csv',error_bad_lines=False)
raw_data_14 = pd.read_csv(loc + '2013-14.csv',error_bad_lines=False)
raw_data_15 = pd.read_csv(loc + '2014-15.csv',error_bad_lines=False)
raw_data_16 = pd.read_csv(loc + '2015-16.csv',error_bad_lines=False)

b'Skipping line 257: expected 48 fields, saw 49\nSkipping line 258: expected 48 fields, saw 49\nSkipping line 259: expected 48 fields, saw 49\nSkipping line 260: expected 48 fields, saw 49\nSkipping line 261: expected 48 fields, saw 49\nSkipping line 262: expected 48 fields, saw 49\nSkipping line 263: expected 48 fields, saw 49\nSkipping line 264: expected 48 fields, saw 49\nSkipping line 265: expected 48 fields, saw 49\nSkipping line 266: expected 48 fields, saw 49\nSkipping line 267: expected 48 fields, saw 49\nSkipping line 268: expected 48 fields, saw 49\nSkipping line 269: expected 48 fields, saw 49\nSkipping line 270: expected 48 fields, saw 49\nSkipping line 271: expected 48 fields, saw 49\nSkipping line 272: expected 48 fields, saw 49\nSkipping line 273: expected 48 fields, saw 51\nSkipping line 274: expected 48 fields, saw 51\nSkipping line 275: expected 48 fields, saw 51\nSkipping line 276: expected 48 fields, saw 51\nSkipping line 277: expected 48 fields, saw 51\nSkipping line 278: expected 48 fields, saw 51\nSkipping line 279: expected 48 fields, saw 51\nSkipping line 280: expected 48 fields, saw 51\nSkipping line 281: expected 48 fields, saw 51\nSkipping line 282: expected 48 fields, saw 51\nSkipping line 283: expected 48 fields, saw 51\nSkipping line 284: expected 48 fields, saw 51\nSkipping line 285: expected 48 fields, saw 51\nSkipping line 286: expected 48 fields, saw 51\nSkipping line 287: expected 48 fields, saw 51\nSkipping line 288: expected 48 fields, saw 51\nSkipping line 321: expected 48 fields, saw 49\nSkipping line 322: expected 48 fields, saw 49\nSkipping line 323: expected 48 fields, saw 49\nSkipping line 324: expected 48 fields, saw 49\nSkipping line 325: expected 48 fields, saw 49\nSkipping line 326: expected 48 fields, saw 49\nSkipping line 327: expected 48 fields, saw 49\nSkipping line 328: expected 48 fields, saw 49\nSkipping line 329: expected 48 fields, saw 49\nSkipping line 330: expected 48 fields, saw 49\nSkipping line 331: expected 48 fields, saw 49\nSkipping line 332: expected 48 fields, saw 49\nSkipping line 333: expected 48 fields, saw 49\nSkipping line 334: expected 48 fields, saw 49\nSkipping line 335: expected 48 fields, saw 49\nSkipping line 336: expected 48 fields, saw 49\nSkipping line 337: expected 48 fields, saw 53\nSkipping line 338: expected 48 fields, saw 53\nSkipping line 339: expected 48 fields, saw 53\nSkipping line 340: expected 48 fields, saw 53\nSkipping line 341: expected 48 fields, saw 53\nSkipping line 342: expected 48 fields, saw 53\nSkipping line 343: expected 48 fields, saw 53\nSkipping line 344: expected 48 fields, saw 53\nSkipping line 345: expected 48 fields, saw 53\nSkipping line 346: expected 48 fields, saw 53\nSkipping line 347: expected 48 fields, saw 53\nSkipping line 348: expected 48 fields, saw 53\nSkipping line 349: expected 48 fields, saw 53\nSkipping line 350: expected 48 fields, saw 53\nSkipping line 351: expected 48 fields, saw 53\nSkipping line 352: expected 48 fields, saw 53\n'
b'Skipping line 305: expected 57 fields, saw 72\nSkipping line 306: expected 57 fields, saw 72\nSkipping line 307: expected 57 fields, saw 72\nSkipping line 308: expected 57 fields, saw 72\nSkipping line 309: expected 57 fields, saw 72\nSkipping line 310: expected 57 fields, saw 72\nSkipping line 311: expected 57 fields, saw 72\nSkipping line 312: expected 57 fields, saw 72\nSkipping line 313: expected 57 fields, saw 72\nSkipping line 314: expected 57 fields, saw 72\nSkipping line 315: expected 57 fields, saw 72\nSkipping line 316: expected 57 fields, saw 72\nSkipping line 317: expected 57 fields, saw 72\nSkipping line 318: expected 57 fields, saw 72\nSkipping line 319: expected 57 fields, saw 72\nSkipping line 320: expected 57 fields, saw 72\nSkipping line 321: expected 57 fields, saw 72\nSkipping line 322: expected 57 fields, saw 72\nSkipping line 323: expected 57 fields, saw 72\nSkipping line 324: expected 57 fields, saw 72\nSkipping line 325: expected 57 fields, saw 72\nSkipping line 326: expected 57 fields, saw 72\nSkipping line 327: expected 57 fields, saw 72\nSkipping line 328: expected 57 fields, saw 72\nSkipping line 329: expected 57 fields, saw 72\nSkipping line 330: expected 57 fields, saw 72\nSkipping line 331: expected 57 fields, saw 72\nSkipping line 332: expected 57 fields, saw 72\nSkipping line 333: expected 57 fields, saw 72\nSkipping line 334: expected 57 fields, saw 72\nSkipping line 335: expected 57 fields, saw 72\nSkipping line 336: expected 57 fields, saw 72\nSkipping line 369: expected 57 fields, saw 62\nSkipping line 370: expected 57 fields, saw 62\nSkipping line 371: expected 57 fields, saw 62\nSkipping line 372: expected 57 fields, saw 62\nSkipping line 373: expected 57 fields, saw 62\nSkipping line 374: expected 57 fields, saw 62\nSkipping line 375: expected 57 fields, saw 62\nSkipping line 376: expected 57 fields, saw 62\nSkipping line 377: expected 57 fields, saw 62\nSkipping line 378: expected 57 fields, saw 62\nSkipping line 379: expected 57 fields, saw 62\nSkipping line 380: expected 57 fields, saw 62\nSkipping line 381: expected 57 fields, saw 62\n'
b'Skipping line 337: expected 57 fields, saw 62\nSkipping line 338: expected 57 fields, saw 62\nSkipping line 339: expected 57 fields, saw 62\nSkipping line 340: expected 57 fields, saw 62\nSkipping line 341: expected 57 fields, saw 62\nSkipping line 342: expected 57 fields, saw 62\nSkipping line 343: expected 57 fields, saw 62\nSkipping line 344: expected 57 fields, saw 62\nSkipping line 345: expected 57 fields, saw 62\nSkipping line 346: expected 57 fields, saw 62\nSkipping line 347: expected 57 fields, saw 62\nSkipping line 348: expected 57 fields, saw 62\nSkipping line 349: expected 57 fields, saw 62\nSkipping line 350: expected 57 fields, saw 62\nSkipping line 351: expected 57 fields, saw 62\nSkipping line 352: expected 57 fields, saw 62\nSkipping line 353: expected 57 fields, saw 62\nSkipping line 354: expected 57 fields, saw 62\nSkipping line 355: expected 57 fields, saw 62\nSkipping line 356: expected 57 fields, saw 62\nSkipping line 357: expected 57 fields, saw 62\nSkipping line 358: expected 57 fields, saw 62\nSkipping line 359: expected 57 fields, saw 62\nSkipping line 360: expected 57 fields, saw 62\nSkipping line 361: expected 57 fields, saw 62\nSkipping line 362: expected 57 fields, saw 62\nSkipping line 363: expected 57 fields, saw 62\nSkipping line 364: expected 57 fields, saw 62\nSkipping line 365: expected 57 fields, saw 62\nSkipping line 366: expected 57 fields, saw 62\nSkipping line 367: expected 57 fields, saw 62\nSkipping line 368: expected 57 fields, saw 62\nSkipping line 369: expected 57 fields, saw 62\nSkipping line 370: expected 57 fields, saw 62\nSkipping line 371: expected 57 fields, saw 62\nSkipping line 372: expected 57 fields, saw 62\nSkipping line 373: expected 57 fields, saw 62\nSkipping line 374: expected 57 fields, saw 62\nSkipping line 375: expected 57 fields, saw 62\nSkipping line 376: expected 57 fields, saw 62\nSkipping line 377: expected 57 fields, saw 62\nSkipping line 378: expected 57 fields, saw 62\nSkipping line 379: expected 57 fields, saw 62\nSkipping line 380: expected 57 fields, saw 62\nSkipping line 381: expected 57 fields, saw 62\n'

# information 
Date = Match D
date (dd/mm/yy)
HomeTeam = Home Team
AwayTeam = Away Team
FTHG and HG = Full Time Home Team Goals
FTAG and AG = Full Time Away Team Goals
FTR and Res = Full Time Result (H=Home Win, D=Draw, A=Away Win)
HTHG = Half Time Home Team Goals
HTAG = Half Time Away Team Goals
HTR = Half Time Result (H=Home Win, D=Draw, A=Away Win)
HST = Home Team Shots on Target
AST = Away Team Shots on Target
HR = Home Team Red Cards
AR = Away Team Red Cards
HY = Home Team Yellow Cards
AY = Away Team Yellow Cards

In [54]:
# Parse data as time 

#Gets all the statistics related to gameplay
                      
columns_req = ['Date','HomeTeam','AwayTeam','FTHG','FTAG','FTR','HTHG','HTAG','HTR','HST','AST','HR','AR','HY','AY']

playing_statistics_1 = raw_data_1[columns_req]                      
playing_statistics_2 = raw_data_2[columns_req]
playing_statistics_3 = raw_data_3[columns_req]
playing_statistics_4 = raw_data_4[columns_req]
playing_statistics_5 = raw_data_5[columns_req]
playing_statistics_6 = raw_data_6[columns_req]
playing_statistics_7 = raw_data_7[columns_req]
playing_statistics_8 = raw_data_8[columns_req]
playing_statistics_9 = raw_data_9[columns_req]
playing_statistics_10 = raw_data_10[columns_req]
playing_statistics_11 = raw_data_11[columns_req]   
playing_statistics_12 = raw_data_12[columns_req]
playing_statistics_13 = raw_data_13[columns_req]
playing_statistics_14 = raw_data_14[columns_req]
playing_statistics_15 = raw_data_15[columns_req]
playing_statistics_16 = raw_data_16[columns_req]

In [57]:
# Gets the goals scored agg arranged by teams and matchweek
def get_goals_scored(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        HTGS = playing_stat.iloc[i]['FTHG']
        ATGS = playing_stat.iloc[i]['FTAG']
        teams[playing_stat.iloc[i].HomeTeam].append(HTGS)
        teams[playing_stat.iloc[i].AwayTeam].append(ATGS)
    
    # Create a dataframe for goals scored where rows are teams and cols are matchweek.
    GoalsScored = pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T
    GoalsScored[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,39):
        GoalsScored[i] = GoalsScored[i] + GoalsScored[i-1]
    return GoalsScored



# Gets the goals conceded agg arranged by teams and matchweek
def get_goals_conceded(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        ATGC = playing_stat.iloc[i]['FTHG']
        HTGC = playing_stat.iloc[i]['FTAG']
        teams[playing_stat.iloc[i].HomeTeam].append(HTGC)
        teams[playing_stat.iloc[i].AwayTeam].append(ATGC)
    
    # Create a dataframe for goals scored where rows are teams and cols are matchweek.
    GoalsConceded = pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T
    GoalsConceded[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,39):
        GoalsConceded[i] = GoalsConceded[i] + GoalsConceded[i-1]
    return GoalsConceded

def get_gss(playing_stat):
    GC = get_goals_conceded(playing_stat)
    GS = get_goals_scored(playing_stat)
   
    j = 0
    HTGS = []
    ATGS = []
    HTGC = []
    ATGC = []

    for i in range(380):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        HTGS.append(GS.loc[ht][j])
        ATGS.append(GS.loc[at][j])
        HTGC.append(GC.loc[ht][j])
        ATGC.append(GC.loc[at][j])
        
        if ((i + 1)% 10) == 0:
            j = j + 1
        
    playing_stat['HTGS'] = HTGS
    playing_stat['ATGS'] = ATGS
    playing_stat['HTGC'] = HTGC
    playing_stat['ATGC'] = ATGC
    
    return playing_stat

playing_statistics_1.drop_duplicates(inplace=True)
playing_statistics_2.drop_duplicates(inplace=True)
playing_statistics_3.drop_duplicates(inplace=True)
playing_statistics_4.drop_duplicates(inplace=True)
playing_statistics_5.drop_duplicates(inplace=True)
playing_statistics_6.drop_duplicates(inplace=True)
playing_statistics_7.drop_duplicates(inplace=True)
playing_statistics_8.drop_duplicates(inplace=True)
playing_statistics_9.drop_duplicates(inplace=True)
playing_statistics_10.drop_duplicates(inplace=True)
playing_statistics_11.drop_duplicates(inplace=True)
playing_statistics_12.drop_duplicates(inplace=True)
playing_statistics_13.drop_duplicates(inplace=True)
playing_statistics_14.drop_duplicates(inplace=True)
playing_statistics_15.drop_duplicates(inplace=True)
playing_statistics_16.drop_duplicates(inplace=True)
# Apply to each dataset
playing_statistics_1 = get_gss(playing_statistics_1)
playing_statistics_2 = get_gss(playing_statistics_2)
playing_statistics_3 = get_gss(playing_statistics_3)
playing_statistics_4 = get_gss(playing_statistics_4)
playing_statistics_5 = get_gss(playing_statistics_5)
playing_statistics_6 = get_gss(playing_statistics_6)
playing_statistics_7 = get_gss(playing_statistics_7)
playing_statistics_8 = get_gss(playing_statistics_8)
playing_statistics_9 = get_gss(playing_statistics_9)
playing_statistics_10 = get_gss(playing_statistics_10)
playing_statistics_11 = get_gss(playing_statistics_11)
playing_statistics_12 = get_gss(playing_statistics_12)
playing_statistics_13 = get_gss(playing_statistics_13)
playing_statistics_14 = get_gss(playing_statistics_14)
playing_statistics_15 = get_gss(playing_statistics_15)
playing_statistics_16 = get_gss(playing_statistics_16)

/home/milad/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/milad/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/milad/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:77: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/milad/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/milad/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:79: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/milad/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/milad/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:81: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/milad/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:82: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/milad/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/milad/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/milad/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/milad/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:86: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/milad/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:87: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/milad/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:88: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/milad/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:89: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/milad/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:90: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/milad/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/milad/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/milad/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/milad/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

ValueError: Shape of passed values is (20, 32), indices imply (20, 38)